FROM eclipse-temurin:21-jdk-alpine
WORKDIR /workspace/app

RUN apk add --no-cache maven

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src

CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=dev"] 